version: "3.9"

services:
  db:
    image: postgis/postgis:15-3.3
    container_name: gis_postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  api:
    build: .
    container_name: gis_fastapi
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db
    volumes:
      - ./backend:/app

volumes:
  postgres_data:
    driver: local
    driver_opts:
      type: none
      device: /path/to/your/local/directory
      o: bind
      